# Generated by Django 5.0.6 on 2024-05-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveSmallIntegerField(verbose_name='Ano Letivo')),
                ('nome_turma', models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E')], max_length=1, verbose_name='Nome da Turma')),
                ('serie', models.CharField(choices=[('F11', '1º Ano'), ('F12', '2º Ano'), ('F13', '3º Ano'), ('F14', '4º Ano'), ('F15', '5º Ano'), ('F26', '6º Ano'), ('F27', '7º Ano'), ('F28', '8º Ano'), ('F29', '9º Ano')], max_length=3, verbose_name='Série da Turma')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Noturno')], max_length=1, verbose_name='Turno da Turma')),
                ('status', models.CharField(choices=[('Iniciando', 'Iniciando'), ('Em andamento', 'Em andamento'), ('Férias', 'Férias'), ('Finalizada', 'Finalizada'), ('Suspensa', 'Suspensa')], default='Iniciando', max_length=20, verbose_name='Status da Turma')),
                ('alunos', models.ManyToManyField(related_name='alunos', to='core.aluno', verbose_name='Alunos')),
                ('disciplinas', models.ManyToManyField(related_name='disciplinas', to='core.disciplina', verbose_name='Disciplinas')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Instituição')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivel', verbose_name='Nível da Série')),
                ('sala_de_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saladeaula', verbose_name='Sala de Aula')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
