# Generated by Django 5.0.6 on 2024-05-23 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dadospessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('uf_naturalizado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viúvo(a)'), ('D', 'Divorciado(a)'), ('U', 'União Estável')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('religiao', models.CharField(blank=True, choices=[('AS', 'Adventista do Sétimo Dia'), ('AG', 'Agnóstico'), ('BU', 'Budismo'), ('CA', 'Candomblé'), ('CR', 'Católicismo'), ('ES', 'Espiritismo'), ('EV', 'Evangélico'), ('HI', 'Hinduísmo'), ('IS', 'Islamismo'), ('JU', 'Judaísmo'), ('TJ', 'Testemunha de Jeová'), ('UM', 'Umbanda'), ('SR', 'Sem Religião')], max_length=2, null=True, verbose_name='Religião')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=50, verbose_name='Nome da Rua/Avenida')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('numero', models.CharField(max_length=25, verbose_name='Número')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=20, verbose_name='Nacionalidade')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('rg_frente_digitalizado', models.FileField(blank=True, null=True, upload_to='documentos/rg/%Y/%m/%d/', verbose_name='RG Frente Digitalizado')),
                ('rg_verso_digitalizado', models.FileField(blank=True, null=True, upload_to='documentos/rg/%Y/%m/%d/', verbose_name='RG Verso Digitalizado')),
                ('cpf_digitalizado', models.FileField(blank=True, null=True, upload_to='documentos/cpf/%Y/%m/%d/', verbose_name='CPF Digitalizado')),
                ('certidao_nascimento_digitalizado', models.FileField(blank=True, null=True, upload_to='documentos/certidao/%Y/%m/%d/', verbose_name='Certidão de Nascimento Digitalizada')),
                ('orgao_expedidor', models.CharField(blank=True, choices=[('SSP', 'Secretaria de Segurança Pública'), ('PC', 'Polícia Civil'), ('DETRAN', 'Departamento de Trânsito'), ('ITEP', 'Instituto Técnico-Científico de Perícia'), ('POLITEC', 'Politec'), ('IGP', 'Instituto-Geral de Perícias'), ('IPC', 'Instituto de Polícia Científica')], max_length=20, null=True, verbose_name='Órgão Expedidor')),
                ('uf_orgao_expedidor', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF do Órgão Expedidor')),
                ('nis', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Identificação Social')),
                ('numero_do_titulo', models.CharField(blank=True, max_length=2, null=True, verbose_name='Número do Título de Eleitor')),
                ('numero_da_zona', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da Zona Eleitoral')),
                ('numero_da_secao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da Seção Eleitoral')),
            ],
            options={
                'verbose_name': 'Dado Pessoal',
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nome_da_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('nome_do_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('uf_naturalizado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=50, verbose_name='Nome da Rua/Avenida')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('numero', models.CharField(max_length=25, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=20, verbose_name='Nacionalidade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('matricula', models.CharField(editable=False, max_length=20, unique=True)),
                ('ano_ingresso', models.DateTimeField(default=2024)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('dados_pessoais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dadospessoais', verbose_name='Dados Pessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Fantasia da Empresa')),
                ('natureza_juridica', models.CharField(blank=True, max_length=70, null=True, verbose_name='Natureza Jurídica da Empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ da Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da Empresa')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone da Empresa')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP da Empresa')),
                ('endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Rua/Avenida')),
                ('bairro', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site da Empresa')),
                ('codigo_inep', models.IntegerField(blank=True, null=True, verbose_name='Código INEP da Instituição')),
                ('nome_diretor', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome do Diretor(a) da Empresa')),
                ('assinatura_diretor', models.FileField(blank=True, null=True, upload_to='', verbose_name='Assinatura do Diretor')),
                ('nome_secretario', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome do Secretario(a) da Empresa')),
                ('assinatura_secretario', models.FileField(blank=True, null=True, upload_to='', verbose_name='Assinatura do Secretário')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmar Dados')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone do setor')),
                ('observacoes', models.TextField(default='Setor da empresa em alta produtividade', verbose_name='Atribuições do Setor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('uf_naturalizado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=50, verbose_name='Nome da Rua/Avenida')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('numero', models.CharField(max_length=25, verbose_name='Número')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=20, verbose_name='Nacionalidade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('matricula', models.CharField(editable=False, max_length=20, unique=True)),
                ('ano_ingresso', models.DateTimeField(default=2024)),
                ('dados_pessoais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='core.dadospessoais', verbose_name='Dados Pessoais')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
