# Generated by Django 4.2.13 on 2024-06-01 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='serie',
            field=models.CharField(choices=[('F11', '1º Ano do Fundamental I'), ('F12', '2º Ano do Fundamental I'), ('F13', '3º Ano do Fundamental I'), ('F14', '4º Ano do Fundamental I'), ('F15', '5º Ano do Fundamental I'), ('F26', '6º Ano do Fundamental II'), ('F27', '7º Ano do Fundamental II'), ('F28', '8º Ano do Fundamental II'), ('F29', '9º Ano do Fundamental II'), ('OUT', 'Outro Nível de Ensino')], default='OUT', max_length=3, verbose_name='Série da Turma'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
