# Generated by Django 5.0.6 on 2024-05-25 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('relacionamento_id', models.IntegerField()),
                ('relacionamento_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BolsaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_concessao', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_concessao', models.DateField(default=django.utils.timezone.now)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.fatura')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PAGO', 'PAGO'), ('ATRASADO', 'ATRASADO'), ('CANCELADO', 'CANCELADO')], default='PENDENTE', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aplicacao', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Inadimplencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.pagamento')),
                ('taxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.taxa')),
            ],
        ),
    ]
