# Generated by Django 4.2.13 on 2024-06-17 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_escolar', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bolsa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bolsa')),
                ('tipo', models.CharField(choices=[('1', 'Percentual'), ('2', 'Valor Fixo')], max_length=50, verbose_name='Tipo da Bolsa')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Despesa')),
                ('categoria', models.CharField(choices=[('1', 'Salário'), ('2', 'Compra de Material'), ('3', 'Infraestrutura'), ('4', 'Serviços Terceirizados'), ('5', 'Manutenção'), ('6', 'Outros')], max_length=50, verbose_name='Categoria da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('descricao', models.TextField(blank=True, max_length=300, verbose_name='Descrição do Pagamento')),
                ('metodo', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bolsa')),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Faturamento')),
                ('categoria', models.CharField(choices=[('1', 'Mensalidade'), ('2', 'Pagamentos Externos'), ('3', 'Vendas'), ('4', 'Livros'), ('5', 'Atividades Complementares'), ('6', 'Outros')], max_length=50, verbose_name='Categoria do Faturamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do Fautramento')),
                ('descricao', models.TextField(blank=True, max_length=300, verbose_name='Descrição do Faturamento')),
            ],
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Multas')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Atrasado'), ('3', 'Pago')], max_length=50, verbose_name='Status')),
                ('pago', models.BooleanField(default=False)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.fatura')),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Mensalidade')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.serie')),
            ],
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_mensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.mensalidade'),
        ),
    ]
