# Generated by Django 4.2.13 on 2024-05-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bolsa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Bolsa')),
                ('tipo', models.CharField(choices=[('1', 'Percentual'), ('2', 'Valor Fixo')], max_length=50, verbose_name='Tipo da Bolsa')),
            ],
        ),
        migrations.RemoveField(
            model_name='taxa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='taxa',
            name='valor_bolsa',
        ),
        migrations.AddField(
            model_name='fatura',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.bolsa'),
        ),
    ]
