# Generated by Django 4.2.13 on 2024-05-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_bolsa_remove_taxa_tipo_remove_taxa_valor_bolsa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='status',
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='valor_bolsa',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bolsa'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
